language: python
python:
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - pytest --cov=./
# Push the results back to codecov
after_success:
  - codecov